# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5388a4496f61b1808b7d542763f6291db56355bd784c33510f6be08af82a3f8d4194a6c44fa967b823800165b10249351b747a20cdca0fb58291dea4a0e051c4

test:
  secret_key_base: 0347d51d32b3aa8257d85e70db43e6b1ece18e520414b3f6cc9767ca5e8ce3842ad9c79261e4c4c485afa328ffcae2af0eead8908d16b489845d23c7da67c5c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
